//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GainEntities : DbContext
    {
        public GainEntities()
            : base("name=GainEntities")
        {
        }

        //public GainEntities(string connectionString)
        //  : base(connectionString)
        //{
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<logtable> logtables { get; set; }
        public virtual DbSet<maccess_menu> maccess_menu { get; set; }
        public virtual DbSet<mactiontype> mactiontypes { get; set; }
        public virtual DbSet<mbrand> mbrands { get; set; }
        public virtual DbSet<mbrandcountry> mbrandcountries { get; set; }
        public virtual DbSet<mcluster> mclusters { get; set; }
        public virtual DbSet<mcostcontrolsite> mcostcontrolsites { get; set; }
        public virtual DbSet<mcosttype> mcosttypes { get; set; }
        public virtual DbSet<mcountry> mcountries { get; set; }
        public virtual DbSet<mlegalentity> mlegalentities { get; set; }
        public virtual DbSet<mmenu> mmenus { get; set; }
        public virtual DbSet<mport> mports { get; set; }
        public virtual DbSet<mregion> mregions { get; set; }
        public virtual DbSet<mregional_office> mregional_office { get; set; }
        public virtual DbSet<mrole> mroles { get; set; }
        public virtual DbSet<msavingtype> msavingtypes { get; set; }
        public virtual DbSet<msourcecategory> msourcecategories { get; set; }
        public virtual DbSet<mstatu> mstatus { get; set; }
        public virtual DbSet<msubcost> msubcosts { get; set; }
        public virtual DbSet<msubcountry> msubcountries { get; set; }
        public virtual DbSet<msubregion> msubregions { get; set; }
        public virtual DbSet<msynimpact> msynimpacts { get; set; }
        public virtual DbSet<myear> myears { get; set; }
        public virtual DbSet<t_cost_actiontype> t_cost_actiontype { get; set; }
        public virtual DbSet<t_initiative> t_initiative { get; set; }
        public virtual DbSet<t_subcostactiontype> t_subcostactiontype { get; set; }
        public virtual DbSet<t_subcostbrand> t_subcostbrand { get; set; }
        public virtual DbSet<t_subcostinitiative> t_subcostinitiative { get; set; }
        public virtual DbSet<user_list> user_list { get; set; }
        public virtual DbSet<vwagency> vwagencies { get; set; }
        public virtual DbSet<vwheaderinitiative> vwheaderinitiatives { get; set; }
        public virtual DbSet<vwsummarydashboard> vwsummarydashboards { get; set; }
        public virtual DbSet<vwsummarydashboarddetail> vwsummarydashboarddetails { get; set; }
        public virtual DbSet<vwtopcategory> vwtopcategories { get; set; }
        public virtual DbSet<vwtypeofsaving> vwtypeofsavings { get; set; }
    }
}
