//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logtable
    {
        public long id { get; set; }
        public string genKey { get; set; }
        public string initnumber { get; set; }
        public Nullable<int> projectyear { get; set; }
        public string tablesName { get; set; }
        public string columnsName { get; set; }
        public string oldValues { get; set; }
        public string newValues { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string updateBy { get; set; }
    }
}
