//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mmenu()
        {
            this.maccess_menu = new HashSet<maccess_menu>();
            this.mmenu1 = new HashSet<mmenu>();
        }
    
        public long id { get; set; }
        public string code { get; set; }
        public string iconcls { get; set; }
        public string label { get; set; }
        public string link { get; set; }
        public string attribute { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> order { get; set; }
        public string position { get; set; }
        public Nullable<long> parent { get; set; }
        public Nullable<bool> publish { get; set; }
        public string linkdependency { get; set; }
        public bool obsolete { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maccess_menu> maccess_menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mmenu> mmenu1 { get; set; }
        public virtual mmenu mmenu2 { get; set; }
    }
}
