//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_list
    {
        public int user_id { get; set; }
        public string USER_FIRST_NAME { get; set; }
        public string USER_MIDDLE_NAME { get; set; }
        public string USER_LAST_NAME { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string PICTURE_PATH { get; set; }
        public int EXTENSION_NO { get; set; }
        public string Company_code { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> levelKdAccess { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> KdAccess { get; set; }
        public string country_right { get; set; }
        public string POD { get; set; }
        public Nullable<int> istoadmin { get; set; }
        public string right_name { get; set; }
        public string cb_right { get; set; }
        public string region_right { get; set; }
        public string costcontrolsite { get; set; }
        public string email { get; set; }
        public Nullable<int> isNew { get; set; }
        public Nullable<int> userType { get; set; }
        public string CompanyCountry { get; set; }
        public string OfficeLocation { get; set; }
        public string Job { get; set; }
        public string encPassword { get; set; }
        public string subcountry_right { get; set; }
        public string subregion_right { get; set; }
        public string RegionalOffice_right { get; set; }
        public string CostControlSite_right { get; set; }
        public string Brand_right { get; set; }
        public string CostItem_right { get; set; }
        public string SubCostItem_right { get; set; }
        public Nullable<int> validity_right { get; set; }
        public Nullable<int> confidential_right { get; set; }
        public string years_right { get; set; }
    }
}
