//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwagency
    {
        public decimal id { get; set; }
        public string CostTypeName { get; set; }
        public Nullable<short> projectyear { get; set; }
        public long jml { get; set; }
        public decimal targetty { get; set; }
        public decimal monthlytarget { get; set; }
        public decimal monthlyachsaving { get; set; }
        public decimal percentty { get; set; }
        public decimal ytdtarget { get; set; }
        public decimal ytdachieved { get; set; }
        public decimal percentytd { get; set; }
        public decimal gap { get; set; }
    }
}
