//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwheaderinitiative
    {
        public long id { get; set; }
        public string InitNumber { get; set; }
        public Nullable<long> SourceCategory { get; set; }
        public string RelatedInitiative { get; set; }
        public Nullable<long> CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<long> SubCountryID { get; set; }
        public string SubCountryName { get; set; }
        public Nullable<long> BrandID { get; set; }
        public string brandname { get; set; }
        public Nullable<long> RegionID { get; set; }
        public string RegionName { get; set; }
        public Nullable<long> SubRegionID { get; set; }
        public string SubRegionName { get; set; }
        public Nullable<long> ClusterID { get; set; }
        public string ClusterName { get; set; }
        public Nullable<long> RegionalOfficeID { get; set; }
        public string RegionalOffice_Name { get; set; }
        public Nullable<long> CostControlID { get; set; }
        public string CostControlSiteName { get; set; }
        public Nullable<long> LegalEntityID { get; set; }
        public string LegalEntityName { get; set; }
        public string Confidential { get; set; }
        public string Description { get; set; }
        public string ResponsibleFullName { get; set; }
        public Nullable<long> InitiativeType { get; set; }
        public string SavingTypeName { get; set; }
        public Nullable<long> CostCategoryID { get; set; }
        public string CostTypeName { get; set; }
        public Nullable<long> SubCostCategoryID { get; set; }
        public string SubCostName { get; set; }
        public Nullable<long> ActionTypeID { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<long> SynergyImpactID { get; set; }
        public string SynImpactName { get; set; }
        public Nullable<System.DateTime> StartMonth { get; set; }
        public Nullable<System.DateTime> EndMonth { get; set; }
        public string LaraCode { get; set; }
        public Nullable<decimal> TargetTY { get; set; }
        public Nullable<decimal> TargetNY { get; set; }
        public string HOValidity { get; set; }
        public string RPOCControl { get; set; }
        public Nullable<long> InitStatus { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> YTDTarget { get; set; }
        public Nullable<decimal> YTDAchieved { get; set; }
        public Nullable<decimal> TargetJan { get; set; }
        public Nullable<decimal> AchJan { get; set; }
        public Nullable<decimal> TargetFeb { get; set; }
        public Nullable<decimal> AchFeb { get; set; }
        public Nullable<decimal> TargetMar { get; set; }
        public Nullable<decimal> AchMar { get; set; }
        public Nullable<decimal> TargetApr { get; set; }
        public Nullable<decimal> AchApr { get; set; }
        public Nullable<decimal> TargetMay { get; set; }
        public Nullable<decimal> AchMay { get; set; }
        public Nullable<decimal> TargetJun { get; set; }
        public Nullable<decimal> AchJun { get; set; }
        public Nullable<decimal> TargetJul { get; set; }
        public Nullable<decimal> AchJul { get; set; }
        public Nullable<decimal> TargetAug { get; set; }
        public Nullable<decimal> AchAug { get; set; }
        public Nullable<decimal> TargetSep { get; set; }
        public Nullable<decimal> AchSep { get; set; }
        public Nullable<decimal> TargetOct { get; set; }
        public Nullable<decimal> AchOct { get; set; }
        public Nullable<decimal> TargetNov { get; set; }
        public Nullable<decimal> AchNov { get; set; }
        public Nullable<decimal> TargetDec { get; set; }
        public Nullable<decimal> AchDec { get; set; }
        public Nullable<decimal> TargetNexJan { get; set; }
        public Nullable<decimal> AchNexJan { get; set; }
        public Nullable<decimal> TargetNexFeb { get; set; }
        public Nullable<decimal> AchNexFeb { get; set; }
        public Nullable<decimal> TargetNexMar { get; set; }
        public Nullable<decimal> AchNexMar { get; set; }
        public Nullable<decimal> TargetNexApr { get; set; }
        public Nullable<decimal> AchNexApr { get; set; }
        public Nullable<decimal> TargetNexMay { get; set; }
        public Nullable<decimal> AchNexMay { get; set; }
        public Nullable<decimal> TargetNexJun { get; set; }
        public Nullable<decimal> AchNexJun { get; set; }
        public Nullable<decimal> TargetNexJul { get; set; }
        public Nullable<decimal> AchNexJul { get; set; }
        public Nullable<decimal> TargetNexAug { get; set; }
        public Nullable<decimal> AchNexAug { get; set; }
        public Nullable<decimal> TargetNexSep { get; set; }
        public Nullable<decimal> AchNexSep { get; set; }
        public Nullable<decimal> TargetNexOct { get; set; }
        public Nullable<decimal> AchNexOct { get; set; }
        public Nullable<decimal> TargetNexNov { get; set; }
        public Nullable<decimal> AchNexNov { get; set; }
        public Nullable<decimal> TargetNexDec { get; set; }
        public Nullable<decimal> AchNexDec { get; set; }
        public string AgencyComment { get; set; }
        public string RPOCComment { get; set; }
        public string HOComment { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<long> PortID { get; set; }
        public string portName { get; set; }
        public string VendorName { get; set; }
        public string UploadedFile { get; set; }
        public int isDeleted { get; set; }
        public Nullable<short> ProjectYear { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
