//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtypeofsaving
    {
        public decimal id { get; set; }
        public string SavingTypeName { get; set; }
        public Nullable<short> projectyear { get; set; }
        public Nullable<decimal> prcnt { get; set; }
        public decimal YTDAchieved { get; set; }
        public decimal YTDTarget { get; set; }
    }
}
