//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maccess_menu
    {
        public long id { get; set; }
        public long roles_id { get; set; }
        public Nullable<long> menu_id { get; set; }
        public Nullable<bool> publish { get; set; }
        public bool obsolete { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual mrole mrole { get; set; }
        public virtual mmenu mmenu { get; set; }
    }
}
