//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcpi
    {
        public long id { get; set; }
        public long mCountry_id { get; set; }
		public string Country_name { get; set; }
		public string Period_type { get; set; }
		public long InitYear { get; set; }
		public int Period_index { get; set; }
		public decimal CPI { get; set; }
		public string Information { get; set; }
		public string Source { get; set; }
		
        public Nullable<long> subcountryid { get; set; }
		
        public virtual mcountry mcountry { get; set; }
    }
}
