//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mrole()
        {
            this.maccess_menu = new HashSet<maccess_menu>();
        }
    
        public long id { get; set; }
        public string role_code { get; set; }
        public string code { get; set; }
        public string def { get; set; }
        public string desc { get; set; }
        public string permission { get; set; }
        public string countries_id { get; set; }
        public bool isFinalRole { get; set; }
        public bool obsolete { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maccess_menu> maccess_menu { get; set; }
    }
}
