//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msubcountry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msubcountry()
        {
            this.mbrandcountries = new HashSet<mbrandcountry>();
            this.mlegalentities = new HashSet<mlegalentity>();
            this.mregional_office = new HashSet<mregional_office>();
            this.t_initiative = new HashSet<t_initiative>();
            this.t_subctry_costcntrlsite = new HashSet<t_subctry_costcntrlsite>();
        }
    
        public long id { get; set; }
        public long CountryID { get; set; }
        public string SubCountryName { get; set; }
        public string CountryCode { get; set; }
        public string isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mbrandcountry> mbrandcountries { get; set; }
        public virtual mcountry mcountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mlegalentity> mlegalentities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mregional_office> mregional_office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_initiative> t_initiative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_subctry_costcntrlsite> t_subctry_costcntrlsite { get; set; }
    }
}
