//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_cost_actiontype
    {
        public long id { get; set; }
        public long costitemid { get; set; }
        public long actiontypeid { get; set; }
        public long InitYear { get; set; }
        public virtual mactiontype mactiontype { get; set; }
        public virtual mcosttype mcosttype { get; set; }
    }
}
