//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_initiative_calcs
    {
        public long id { get; set; }
        public long t_initiative_ID { get; set; }

        public decimal jan_Actual_CPU_Nmin1 { get; set; }
        public decimal feb_Actual_CPU_Nmin1 { get; set; }
        public decimal march_Actual_CPU_Nmin1 { get; set; }
        public decimal apr_Actual_CPU_Nmin1 { get; set; }
        public decimal may_Actual_CPU_Nmin1 { get; set; }
        public decimal jun_Actual_CPU_Nmin1 { get; set; }
        public decimal jul_Actual_CPU_Nmin1 { get; set; }
        public decimal aug_Actual_CPU_Nmin1 { get; set; }
        public decimal sep_Actual_CPU_Nmin1 { get; set; }
        public decimal oct_Actual_CPU_Nmin1 { get; set; }
        public decimal nov_Actual_CPU_Nmin1 { get; set; }
        public decimal dec_Actual_CPU_Nmin1 { get; set; }
        public decimal jan_Target_CPU_N { get; set; }
        public decimal feb_Target_CPU_N { get; set; }
        public decimal march_Target_CPU_N { get; set; }
        public decimal apr_Target_CPU_N { get; set; }
        public decimal may_Target_CPU_N { get; set; }
        public decimal jun_Target_CPU_N { get; set; }
        public decimal jul_Target_CPU_N { get; set; }
        public decimal aug_Target_CPU_N { get; set; }
        public decimal sep_Target_CPU_N { get; set; }
        public decimal oct_Target_CPU_N { get; set; }
        public decimal nov_Target_CPU_N { get; set; }
        public decimal dec_Target_CPU_N { get; set; }
        public decimal jan_A_Price_effect { get; set; }
        public decimal feb_A_Price_effect { get; set; }
        public decimal march_A_Price_effect { get; set; }
        public decimal apr_A_Price_effect { get; set; }
        public decimal may_A_Price_effect { get; set; }
        public decimal jun_A_Price_effect { get; set; }
        public decimal jul_A_Price_effect { get; set; }
        public decimal aug_A_Price_effect { get; set; }
        public decimal sep_A_Price_effect { get; set; }
        public decimal oct_A_Price_effect { get; set; }
        public decimal nov_A_Price_effect { get; set; }
        public decimal dec_A_Price_effect { get; set; }
        public decimal jan_A_Volume_Effect { get; set; }
        public decimal feb_A_Volume_Effect { get; set; }
        public decimal march_A_Volume_Effect { get; set; }
        public decimal apr_A_Volume_Effect { get; set; }
        public decimal may_A_Volume_Effect { get; set; }
        public decimal jun_A_Volume_Effect { get; set; }
        public decimal jul_A_Volume_Effect { get; set; }
        public decimal aug_A_Volume_Effect { get; set; }
        public decimal sep_A_Volume_Effect { get; set; }
        public decimal oct_A_Volume_Effect { get; set; }
        public decimal nov_A_Volume_Effect { get; set; }
        public decimal dec_A_Volume_Effect { get; set; }
        public decimal jan_Achievement { get; set; }
        public decimal feb_Achievement { get; set; }
        public decimal march_Achievement { get; set; }
        public decimal apr_Achievement { get; set; }
        public decimal may_Achievement { get; set; }
        public decimal jun_Achievement { get; set; }
        public decimal jul_Achievement { get; set; }
        public decimal aug_Achievement { get; set; }
        public decimal sep_Achievement { get; set; }
        public decimal oct_Achievement { get; set; }
        public decimal nov_Achievement { get; set; }
        public decimal dec_Achievement { get; set; }
        public decimal jan_ST_Price_effect { get; set; }
        public decimal feb_ST_Price_effect { get; set; }
        public decimal march_ST_Price_effect { get; set; }
        public decimal apr_ST_Price_effect { get; set; }
        public decimal may_ST_Price_effect { get; set; }
        public decimal jun_ST_Price_effect { get; set; }
        public decimal jul_ST_Price_effect { get; set; }
        public decimal aug_ST_Price_effect { get; set; }
        public decimal sep_ST_Price_effect { get; set; }
        public decimal oct_ST_Price_effect { get; set; }
        public decimal nov_ST_Price_effect { get; set; }
        public decimal dec_ST_Price_effect { get; set; }
        public decimal jan_ST_Volume_Effect { get; set; }
        public decimal feb_ST_Volume_Effect { get; set; }
        public decimal march_ST_Volume_Effect { get; set; }
        public decimal apr_ST_Volume_Effect { get; set; }
        public decimal may_ST_Volume_Effect { get; set; }
        public decimal jun_ST_Volume_Effect { get; set; }
        public decimal jul_ST_Volume_Effect { get; set; }
        public decimal aug_ST_Volume_Effect { get; set; }
        public decimal sep_ST_Volume_Effect { get; set; }
        public decimal oct_ST_Volume_Effect { get; set; }
        public decimal nov_ST_Volume_Effect { get; set; }
        public decimal dec_ST_Volume_Effect { get; set; }
        public decimal jan_FY_Secured_Target { get; set; }
        public decimal feb_FY_Secured_Target { get; set; }
        public decimal march_FY_Secured_Target { get; set; }
        public decimal apr_FY_Secured_Target { get; set; }
        public decimal may_FY_Secured_Target { get; set; }
        public decimal jun_FY_Secured_Target { get; set; }
        public decimal jul_FY_Secured_Target { get; set; }
        public decimal aug_FY_Secured_Target { get; set; }
        public decimal sep_FY_Secured_Target { get; set; }
        public decimal oct_FY_Secured_Target { get; set; }
        public decimal nov_FY_Secured_Target { get; set; }
        public decimal dec_FY_Secured_Target { get; set; }
        public decimal jan_CPI_Effect { get; set; }
        public decimal feb_CPI_Effect { get; set; }
        public decimal march_CPI_Effect { get; set; }
        public decimal apr_CPI_Effect { get; set; }
        public decimal may_CPI_Effect { get; set; }
        public decimal jun_CPI_Effect { get; set; }
        public decimal jul_CPI_Effect { get; set; }
        public decimal aug_CPI_Effect { get; set; }
        public decimal sep_CPI_Effect { get; set; }
        public decimal oct_CPI_Effect { get; set; }
        public decimal nov_CPI_Effect { get; set; }
        public decimal dec_CPI_Effect { get; set; }

        public decimal jan_CPI { get; set; }
        public decimal feb_CPI { get; set; }
        public decimal mar_CPI { get; set; }
        public decimal apr_CPI { get; set; }
        public decimal may_CPI { get; set; }
        public decimal jun_CPI { get; set; }
        public decimal jul_CPI { get; set; }
        public decimal aug_CPI { get; set; }
        public decimal sep_CPI { get; set; }
        public decimal oct_CPI { get; set; }
        public decimal nov_CPI { get; set; }
        public decimal dec_CPI { get; set; }


        public virtual t_initiative t_initiative { get; set; }
    }
}
