//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_subctry_costcntrlsite
    {
        public long id { get; set; }
        public long subcountryid { get; set; }
        public long costcontrolid { get; set; }
    
        public virtual mcostcontrolsite mcostcontrolsite { get; set; }
        public virtual msubcountry msubcountry { get; set; }
    }
}
