//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_subcostactiontype
    {
        public long id { get; set; }
        public Nullable<long> subcostid { get; set; }
        public Nullable<long> actiontypeid { get; set; }
    
        public virtual mactiontype mactiontype { get; set; }
        public virtual msubcost msubcost { get; set; }
    }
}
