//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_subcostinitiative
    {
        public long id { get; set; }
        public Nullable<long> savingtypeid { get; set; }
        public Nullable<long> costitemid { get; set; }
        public Nullable<long> subcostid { get; set; }
        public long InitYear { get; set; }
        public virtual mcosttype mcosttype { get; set; }
        public virtual msavingtype msavingtype { get; set; }
        public virtual msubcost msubcost { get; set; }
    }
}
