//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwsummarydashboard
    {
        public decimal id { get; set; }
        public string RegionName { get; set; }
        public string CountryName { get; set; }
        public Nullable<short> ProjectYear { get; set; }
        public long jml { get; set; }
        public decimal TargetTY { get; set; }
        public decimal monthlytarget { get; set; }
        public decimal monthlyachsaving { get; set; }
        public decimal percentty { get; set; }
        public decimal YTDTarget { get; set; }
        public decimal YTDAchSaving { get; set; }
        public decimal percentytd { get; set; }
        public decimal gap { get; set; }
    }
}
